### ISSUE TITLE
Tally ERP 9 Release 6.3.3 Error T0027

### ISSUE THREAD

**Issue by axoblade** [tejavarma-aln/QrCodeForPayments-Compiled#1]
Tally ERP 9 Release 6.3.3 Error T0027 , the attribute definition started without a valid description

**Comment by tejavarma-aln** [comment]
I tested on 6.3.3 , didn't found any error and also source code(PaymenstQr.txt)  of TDL is available in the repository check once.

**Comment by axoblade** [comment]
fixed, thanks for the hardwork comrade
