### ISSUE TITLE
QR code not working 

### ISSUE THREAD

**Issue by ashokgupta2121** [tejavarma-aln/QrCodeForPayments-Compiled#2]
Sir ji namaskar QR code is not working in tally prime please chack and UPDATE thanks

**Comment by tejavarma-aln** [comment]
It not work in prime 
In prime you can generate QR with TDL no need of this one

**Comment by tejavarma-aln** [comment]
For Prime 1.1. :
https://github.com/tejavarma-aln/QrCodeForPayments-Compiled/blob/master/QrCodeNoDLL/PaymentQrPrime.tdl

**Comment by kailasrvisapure** [comment]
Hello Sir,
I'm able to generate QR code as per instructions, but in print there is no qr printing. The Directory of qr code holds images of qr for each invoice and proper amount and all. Only in print it's not printing. Please help
