### ISSUE TITLE
Payment does not get completed. 

### ISSUE THREAD

**Issue by MrDeadpool786** [tejavarma-aln/QrCodeForPayments-Compiled#4]
I got QR Printed on my Invoice but while receiving payment through UPI Mode Selected I am getting the following error as attached.
and by choosing a bank account and IFSC mode and entering the account number the zero "0" from the start of the account number is getting removed. For Eg my Account No is 0571 then tally is taking it as 571 only.

![WhatsApp Image 2021-01-23 at 7 27 36 PM](https://user-images.githubusercontent.com/77791688/105623972-0a635080-5e44-11eb-8fbc-462ac1e6474e.jpeg)

**Comment by tejavarma-aln** [comment]
its fixed now
update your TDL file only from repository
no need to update other files

**Comment by MrDeadpool786** [comment]
Thank you. Now working correctly.
