### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by pratikgovindani** [tejavarma-aln/QrCodeForPayments-Compiled#5]
it gives an error "The qr code is invalid while scanning for payment" in Tally Prime Release 1.1

it also removes terms of delivery from the invoice.

can this be modified to this?
[
<img width="453" alt="Screenshot 2021-02-27 at 1 16 46 PM" src="https://user-images.githubusercontent.com/79740025/109381079-1a1bfc00-78fe-11eb-96e0-5abfbe8a6e81.png">
](url)

**Comment by tejavarma-aln** [comment]
The QR  code you attached contains some link to the dropbox site
it's not the payment link.
and moreover, terms of delivery is removed to accommodate space for QR Code

**Comment by pratikgovindani** [comment]
its the image of qr code that I got from someones tally invoice (Just a reference for the placement of QR Code)

**Comment by pratikgovindani** [comment]
<img width="453" alt="82623357-A182-4347-8442-42ADE4C46BAF" src="https://user-images.githubusercontent.com/79740025/109408864-902e6a80-79b3-11eb-836b-016ce2378104.png">

**Comment by tejavarma-aln** [comment]
is it solved?

**Comment by pratikgovindani** [comment]
nope i am sending you the qr code

**Comment by pratikgovindani** [comment]
<img width="214" alt="Screenshot 2021-03-01 at 11 41 14 AM" src="https://user-images.githubusercontent.com/79740025/109458556-0bab1d00-7a83-11eb-9acf-034c6e4cbeb0.png">

this is the code being generated using the provided code

**Comment by pratikgovindani** [comment]
Sir,

Can we modify the codes to achieve the billow shown image

<img width="453" alt="Screenshot 2021-02-27 at 1 16 46 PM" src="https://user-images.githubusercontent.com/79740025/109459130-321d8800-7a84-11eb-9168-06e3c547de23.png">

**Comment by tejavarma-aln** [comment]
> Sir,
> 
> Can we modify the codes to achieve the billow shown image
> 
> <img alt="Screenshot 2021-02-27 at 1 16 46 PM" width="453" src="https://user-images.githubusercontent.com/79740025/109459130-321d8800-7a84-11eb-9168-06e3c547de23.png">

Yes you can modify the TDL code
you have to customize that terms part into two parts
on for terms and other for QR image

**Comment by pratikgovindani** [comment]
sir can you help me with that as i am a beginner

**Comment by pratikgovindani** [comment]
> <img alt="Screenshot 2021-03-01 at 11 41 14 AM" width="214" src="https://user-images.githubusercontent.com/79740025/109458556-0bab1d00-7a83-11eb-9acf-034c6e4cbeb0.png">
> 
> this is the code being generated using the provided code

sir,

Has this been resolved?

**Comment by tejavarma-aln** [comment]
> > <img alt="Screenshot 2021-03-01 at 11 41 14 AM" width="214" src="https://user-images.githubusercontent.com/79740025/109458556-0bab1d00-7a83-11eb-9acf-034c6e4cbeb0.png">
> > this is the code being generated using the provided code
> 
> sir,
> 
> Has this been resolved?

Not yet.

**Comment by tejavarma-aln** [comment]
it's not possible as if we constrained the dimensions of QR Code
it will not be scannable
better to shift it to somewhere, if you want terms

**Comment by pratikgovindani** [comment]
> it's not possible as if we constrained the dimensions of QR Code
> it will not be scannable
> better to shift it to somewhere, if you want terms

ok no issues and what about the error while scanning the qr code it gives error that the code is invalid can that be rectified?
